import os
import streamlit as st

# settings.py などの環境設定ファイル
IS_TEST_MODE = True  # 🧪 ローカルテスト時は True。本番リリース時はここを False にするだけでボタンが消滅します。

# supabaseのストレージURL
# 💡 外部の設定からのみ、絶対にURLを取得する形に固定
_url = os.environ.get("SUPABASE_STORAGE_URL", "").strip()

if not _url:
    # Renderでなければ、PCの secrets.toml から引っ張る
    try:
        _url = st.secrets["STORAGE_BASE_URL"].strip()
    except:
        _url = ""

# 🚨 万が一、他のコードが localhost と決めつけていたらここで完全に上書きガード
if _url:
    if not _url.endswith("/"):
        _url += "/"
    STORAGE_BASE_URL = _url
else:
    # 何も設定が取れなかった場合の最低限の安全弁
    STORAGE_BASE_URL = "https://supabase.co"

# 🔍 デバッグ用：今どのURLが設定されたかをVS Codeのターミナルに強制表示させて確認する
print(f"📦 [DEBUG] 現在システムが認識しているストレージURL: {STORAGE_BASE_URL}")


# --- 残りの既存コード ---

# settings.py
# UI表示文字列を集中管理する辞書をここに置きます。
# 必要に応じてこのファイルだけ編集すれば表示文言を一括変更できます。

LABELS = {
    # ログイン
    "login_title": "## 🔐 採点者ログイン画面",
    "input_id_placeholder": "採点者IDを入力してください",
    "input_pass_placeholder": "パスワードを入力",
    "login_button": "ログイン",

    # タブラベル
    "tab1_label": "採点画面",
    "tab2_group_label": "採点状況管理画面",
    "tab3_label": "CSVデータ取込画面",
    "tab4_label": "ファイルのアップロード & ダウンロード",

    # Tab1
    "tab1_header": "採点画面",
    "tab2_group_header": "採点管理画面",
    "refresh_button": "最新の情報に更新",
    "col_grader": "採点者ID",
    "col_response": "問題ID",
    "col_count": "総採点数",
    "col_ungraded": "未採点数",
    "col_graded": "採点済数",
    "col_action": "採点開始",
    "col_grader_name": "採点担当者",
    "start_success": "🎉 選択されたレスポンス識別子 {resp} の採点を開始します！",

    # Tab2
    "tab3_header": "採点振り分け情報付きデータアップロード",
    "tab2_header": "## CSVファイルのアップロード",
    "csv_uploader": "CSVファイルを選択してください",
    "csv_preview": "・取り込みデータプレビュー（CSV内の全データ: 計 {n} 件）",
    "db_insert_btn": "DBへ登録を実行",
    "db_success": "正常に {n} 件のデータを登録しました！",

    # Tab3
    "tab3_title": "## ファイルの UL & DL",
    "tab3_upload_section": "## 1. ファイルのアップロード",
    "file_uploader": "ファイルを選択してください",
    "download_header": "2. ファイルのダウンロード",
    "download_btn": "サンプルテキストをダウンロード",

    # 共通
    "app_title": "## 📊 試験データ管理システム",
    "logout": "ログアウト",
    "confirm_yes": "✅ はい、実行します",
    "confirm_no": "❌ いいえ、戻ります",
    "login_timeout": "⏳ 一定時間操作がなかったため、安全のため自動ログアウトし、編集ロックをすべて解放しました。",
    "no_visible_tabs": "表示対象のタブがありません。管理者にお問い合わせください。(role_id: {role_id})",

    # ログイン
    "login_user_id": "採点者ID",
    "login_password": "パスワード",
    "force_unlock": "🔓 ログイン状態を強制解除",
    "login_required_fields": "採点者IDとパスワードの両方を入力してください。",
    "login_debug_time": "🔍 [デバッグ情報] 経過: {elapsed}秒 / 制限: {limit}秒 (DB値: {db_value})",
    "login_time_error": "⚠️ 時刻判定エリアでエラー: {error} (元データ: {db_value})",
    "login_already_active": "❌ このアカウントは既に他の端末でログイン中です（二重ログイン防止）。",
    "login_success": "ログインに成功しました！",
    "login_invalid_credentials": "採点者IDまたはパスワードが正しくありません。",
    "login_error": "認証エラーが発生しました: {error}",
    "unlock_required_fields": "認証解除を行うには、対象の採点者IDとパスワードを正しく入力してください。",
    "unlock_success": "🔓 ログイン状態、および掴んでいた問題のレコードロックを正常に強制解除しました。もう一度ログインを試みてください。",
    "unlock_invalid_credentials": "採点者IDまたはパスワードが正しくありません。ロック解除に失敗しました。",
    "unlock_error": "解除処理中にエラーが発生しました: {error}",

    # 採点一覧・個別採点
    "loading_data": "データを受信中...",
    "display_filter": "##### 🔍 表示フィルター",
    "question_filter_active": "⏳ 未採点・保留ありのグループのみ表示",
    "question_filter_expired": "⏰ 採点完了日超過も表示",
    "question_no_filtered_data": "✨ 現在、表示条件に該当する採点対象データはありません！",
    "question_count": "表示中の問題パターン数",
    "question_no_data": "💡 現在、データベース内に有効な採点対象レコードが割り当てられていません。",
    "question_list_error": "一覧取得エラーが発生しました: {error}",
    "question_grading_title": "🔍 採点中: {title}",
    "question_context": "担当採点者: {grader} | 問題ID: {response} | 採点完了日: {date}",
    "back_to_question_list": "⬅️ 問題一覧に戻る",
    "loading_question_records": "採点対象データを読み込み中...",
    "question_records_not_found": "採点対象のレコードが見つかりませんでした。",
    "question_locked": "⚠️ この問題は現在、別の採点者（ID: {grader}）が画面を開いて採点中のため、ロックされています。",
    "question_locked_readonly": "💡 内容の閲覧は可能ですが、判定ボタンの操作やメモの書き込みはバッティング防止のため制限されます。",
    "answer_information": "### 📝 採点基準・AI判定情報",
    "answer_label": "**【児童生徒の解答】**",
    "ai_checkpoint_1": "**🤖 AI採点チェックポイント1**",
    "ai_checkpoint_2": "**🤖 AI採点チェックポイント2**",
    "ai_checkpoint_3": "**🤖 AI採点チェックポイント3**",
    "ai_reason": "**💡 AI採点判断理由**",
    "ai_result": "**🤖 AI採点結果**",
    "grading_input": "### 🗂️ 採点・コメント入力",
    "correct_image": "**🎯 採点基準画像** ※クリックで別タブで拡大",
    "image_missing": "⚠️ 採点基準画像ファイル名が登録されていません。",
    "image_load_skipped": "（画像読み込みスキップ: {error}）",
    "current_status": "**現在の採点状況:** {status}",
    "question_number": "📄 {current}問目（{total}問中）",
    "admin_locked": "🔒 この問題は管理者によって判定が確定しているため、上書き変更はロックされています（閲覧専用）。",
    "select_judgement": "採点判定を選択してください（ボタンを押すと即時保存して次の問題へ進みます）：",

    # 採点管理
    "no_group": "あなたの所属グループ情報がありません。管理者にお問い合わせください。",
    "no_graders": "対象の採点者が見つかりません。",
    "all_pattern_count": "全体の担当総集計パターン数",
    "group_pattern_count": "グループ内の担当総集計パターン数",
    "progress_filter_active": "📝 要採点（未採点あり）を表示",
    "progress_filter_completed": "✅ 採点完了分を表示",
    "progress_filter_expired": "⏰ 過去の採点完了日分を表示",
    "grader_filter": "👤 担当採点者で絞り込み (未選択時は全表示)",
    "filtered_count": "💡 フィルター適用後の表示件数: {count} 件",
    "no_scoring_data": "対象の採点データが見つかりません。",
    "bulk_open": "🔽 一括変更を開く",
    "bulk_close": "🔼 一括変更を閉じる",
    "bulk_instruction": "↓チェックした行を一括変更↓",
    "bulk_update": "一括更新",
    "change_grader": "採点者変更",
    "edit_grader": "🔓 変更する",
    "change": "変更",
    "select_grader": "変更する採点者を選択してください。",
    "bulk_select_required": "⚠️ 一括変更する行を選択し、かつ対象行の「🔓 変更する」チェックボックスをONにしてロックを解除してください。",
    "bulk_target_required": "一括変更先の採点者WEBIDを選択してください。",
    "loading_bulk_update": "未採点レコードを抽出して一括更新中...",
    "bulk_update_skipped": "⚠️ 対象行に未採点の問題が残っていなかったため、更新はスキップされました。",
    "bulk_update_error": "❌ 一括更新エラー: {error}",
    "progress_load_error": "データ取得中にエラーが発生しました: {error}",
    "grader_master_error": "⚠️ 採点者マスタの取得に失敗しました: {error}",
    "row_number": "行番号",
    "completion_date": "採点完了日",
    "total_count": "総採点数",
    "ungraded_count": "未採点数",
    "graded_count": "採点済数",
    "hold_count": "採点保留数",
    "bulk_update_success": "🔓 未採点レコード {count} 件の担当者を変更しました。",
    "bulk_confirm": "🗂️ **一括更新の確認**\n\n選択された **{count} 件** の行から、**未採点問題のみ（白紙・空文字含む）** を抽出し担当者を一括変更します。\n対象行番号: {rows}\n➡️ **変更後WEBID: {grader}**",
    "bulk_update_no_target": "対象行に未採点の問題が残っていなかったため、更新はスキップされました。",
    "bulk_update_done": "🎉 正常に {groups} グループ（計 {records} 件の未採点レコード）を一括更新しました！",
    "bulk_no_rows": "対象の採点データが見つかりません。",
    "danger_success": "💥 問題管理テーブルの全データを正常に物理削除・初期化しました！",
    "danger_error": "物理削除の実行に失敗しました: {error}",
    "danger_title": "### 🛠️ 管理者テスト用デバッグツール",
    "danger_description": "※このエリアは「🛠️ テスト用デバッグ」タブのトグルスイッチがオンの時だけ自動的に露出します。",
    "danger_confirm": "⚠️ 本当に全ての問題データを完全に削除してもよろしいですか？（元に戻せません）",
    "danger_delete": "🔥 問題テーブルの全データを物理削除する",

    # CSV入出力
    "csv_import_description": "**取り込みたいCSVフォルダ内のファイルをすべて選択するか、フォルダをそのまま以下の枠内にドラッグ＆ドロップしてください**",
    "csv_folder_uploader": "取り込むCSVフォルダ内のファイルをまとめて選択・ドロップしてください",
    "csv_read_skip": "⚠️ {file} は読み込めないか、空のためスキップしました。",
    "csv_missing_columns": "❌ {file} に必須カラムが不足しています: {columns}",
    "csv_no_valid_data": "有効なCSVデータがありませんでした。",
    "csv_file_count": "📂 読み込んだファイル数: **{count} 個**",
    "csv_total_preview": "📊 **全ファイル合計プレビュー: {count}件のデータが統合されました**",
    "csv_upload_success": "アップロード完了: {file}",
    "file_size": "ファイルサイズ:",
    "sample_text": "これはサンプルテキストです。\n必要に応じて内容を更新して保存してください。",
    "data_io_title": "📥 採点用データ管理（出力＆AI結果反映）",
    "ai_download_tab": "AI採点用データダウンロード",
    "ai_upload_tab": "AI採点結果アップロード",
    "unprocessed_export": "##### 1. 未処理データの出力",
    "fetch_unprocessed": "🔍 対象データを抽出・プレビュー",
    "loading_unprocessed": "データベースから未登録データを抽出中...",
    "unprocessed_found": "🎯 未登録のレコードが **{count} 件** 見つかりました。",
    "download_csv": "📥 抽出データをCSVでダウンロード",
    "unprocessed_none": "✨ 現在、AI採点判定（`ai_judge_mark`）が未登録のレコードはありません。",
    "csv_format_title": "##### 2. 採点結果CSVのアップロード登録",
    "csv_utf8_only": "⚠️ 取り込み可能なCSVファイルは **UTF-8（BOMあり）形式のみ** です。",
    "csv_format_details": "詳細なCSVフォーマット要件を確認する",
    "csv_required_columns": "以下の**7つのカラム**がすべて含まれている必要があります（並び順は自由です）。",
    "result_csv_uploader": "採点結果CSVファイルを選択してください",
    "invalid_encoding": "❌ ファイルの文字コードが正しくありません。UTF-8（BOMあり）形式のCSVファイルをアップロードしてください。",
    "empty_upload": "⚠️ アップロードされたファイルは空です。",
    "required_columns_missing": "❌ 必須カラムが不足しています: {columns}",
    "result_preview": "📊 **読み込みプレビュー: {count} 件のデータが正常にパースされました**",
    "register_results": "🔥 採点結果をデータベースに登録（一括更新）",
    "empty_primary_keys": "❌ `saiten_question_id` が空の行が {count} 件あります。これらは登録できません。",
    "export_title": "📤 採点完了データ出力",
    "export_description": "採点完了日ごとに集計を行い、**すべての採点が完了している日付のデータのみ**を選択してCSVダウンロードできます。",
    "export_date_list": "### 📅 採点完了日ごとの集計一覧",
    "extract_selected_dates": "🔍 選択した日付の採点完了データを抽出する",
    "select_export_date": "⚠️ 出力したい採点完了日の「選択」チェックボックスにチェックを入れてください。",
    "download_step": "📢 **ステップ1: ファイルのダウンロード**",
    "commit_step": "📢 **ステップ2: システムへの完了報告**",
    "commit_export": "🔥 上記データのダウンロード完了をシステムに確定報告（出力済に更新）",
    "file_upload_complete": "アップロード完了: {file}",
    "file_size_label": "ファイルサイズ:",
    "csv_success_registering": "すべてのデータを一括登録中...",
    "graded_data_download": "📥 選択した採点完了データを結合CSVでダウンロード",
    "csv_data_error": "データ抽出エラーが発生しました: {error}",
    "csv_processing_error": "❌ ファイル処理中にエラーが発生しました: {error}",
    "csv_db_error": "データベース登録エラー: {error}",
    "csv_read_error": "ファイル読み込みエラーが発生しました: {error}",
    "result_data_error": "❌ データベースの検証中にエラーが発生しました: {error}",
    "result_update_error": "❌ チャンク更新中にエラーが発生しました（インデックス {index}〜）: {error}",
    "result_update_success": "✅ 合計 {count} 件のAI採点結果（更新日時含む）を正常に反映・更新しました！",
    "result_integrity_check": "データの整合性を検証中...",
    "result_db_update": "Supabaseのデータを更新中...",
    "result_registration": "🔥 採点結果をデータベースに登録（一括更新）",
    "graded_export_loading": "データベースから最新の採点状況を集計中...",
    "graded_export_error": "データの読み込みに失敗しました: {error}",
    "graded_export_no_data": "💡 データベースにレコードが存在しません。",
    "graded_export_no_dates": "💡 集計対象となる有効な採点完了日（日付データ）がありません。",
    "graded_filter_all": "すべて表示",
    "graded_filter_available": "🟢 出力可能 のみ",
    "graded_filter_unavailable": "🔴 出力不可 のみ",
    "graded_display_count": "表示中: {displayed} 件 / 全件: {total} 件",
    "graded_invalid_date": "❌ 選択された日付の中に、まだ採点作業が完了していない日付が含まれています。",
    "graded_ready": "🎯 出力準備完了: **{count} 件** （対象日: {dates}）",
    "graded_commit_loading": "操作監査ログに一括確定を刻印中...",
    "graded_commit_success": "✅ 監査操作ログにミリ秒刻印し、出力ステータスを同期しました！",
    "graded_commit_error": "確定報告処理中にエラーが発生しました: {error}",
    "graded_preview": "##### 📝 出力対象データ プレビュー (先頭50件)",

    # 保留管理
    "hold_access_denied": "❌ この画面のアクセス権限がありません。特権管理者のみがアクセス可能です。",
    "hold_master_error": "採点者マスタの取得に失敗しました: {error}",
    "hold_title": "🟣 保留（H）レコード集中確認・再採点",
    "hold_description": "現在解決していない **「保留（H）」** 判定、または過去の対応履歴データを集計しています。",
    "hold_refresh": "🔄 保留データを更新",
    "hold_loading": "データベースから保留データを抽出中...",
    "hold_filter_title": "##### 🔍 保留データ表示フィルター",
    "hold_filter_active": "🔴 未対応の保留あり",
    "hold_filter_mine": "🔵 自分が対応済のみ",
    "hold_filter_others": "🟢 自分以外が対応済のみ",
    "hold_filter_past": "🗃️ 過去の採点完了日分も表示",
    "hold_no_match": "✨ 条件に一致する保留データ、または対応履歴はありません。",
    "hold_count": "表示中の保留総パターン数",
    "hold_no_data": "✨ 現在、データベース内に保留データはありません！すべての判定が完了しています。",
    "hold_error": "データ取得エラー: {error}",
    "hold_grading_title": "🟣 保留解除・再採点中: {title}",
    "hold_context": "対象採点者: {grader} | 問題ID: {response}",
    "back_to_hold_list": "⬅️ 保留問題一覧に戻る",
    "hold_records_loading": "保留レコードを読み込み中...",
    "hold_target_missing": "💡 対象データが見つかりませんでした。一度一覧へ戻ります。",
    "hold_input_title": "### 🗂️ 再採点入力（保留解除）",
    "correct_standard": "**🎯 正答基準** ※クリックで別タブで拡大",
    "hold_locked": "🔒 この問題は現在、採点者（ID: {grader}）が画面を開いて採点中のため、ロックされています（閲覧専用）。",
    "hold_select_judgement": "判定を選択して上書き修正・確定してください：",
    "hold_score_correct": "🟢 正答(O)",
    "hold_score_wrong": "🔴 誤答(X)",
    "hold_score_none": "⚪ 無答(*)",
    "hold_status": "確定済({status})",
    "approver": "👤 確定者: {name}",
    "approver_none": "👤 確定者: なし（初期状態）",
    "memo_label": "採点メモ / コメントの修正",
    "navigation": "📂 **レコード移動・ナビゲーション**",
    "first_record": "⏪ 先頭へ戻る",
    "previous_unprocessed": "⏮️ 前の未処理へ",
    "previous": "◀ 前へ",
    "next": "次へ ▶",
    "next_unprocessed": "⏭️ 次の未処理へ",
    "admin_next": "👑 管理者対応へ",
    "remaining_hold": "保留問題残り：",
    "admin_jump": "🔄 後方に該当データがないため、先頭に戻って管理者確定レコードへワープしました。",
    "no_admin_record": "✨ このグループ内に、管理者が対応した保留レコードはありません。",
    "hold_saving": "判定を上書き保存中...",
    "hold_save_success": "🎯 判定「{score}」で正常に保存しました！",
    "hold_finish_title": "🎉 保留解除・採点完了の確認",
    "hold_finish_heading": "##### ✨ これで最後の保留データの採点が終了しました！",
    "hold_finish_message": "最終判定の上書き保存は完了しています。このまま問題一覧画面に戻りますか？それとも内容を見直しますか？",
    "hold_finish_hint": "（※そのまま **Enterキー** を押すと一覧に戻ります）",
    "hold_finish_submit": "✅ このまま登録をして一覧に戻る",
    "hold_review_again": "🔍 もう一度採点を見直す",
    "hold_update_error": "データベースの更新に失敗しました: {error}",
    "logged_in_user": "ログイン中: {name} (採点者ID: {user_id}) / Role: {role}",
    "debug_tab_description": "このタブは特権管理者（role_id=4）にのみ露出する安全な検証エリアです。",
    "test_mode_enabled": "🟢 現在テストモードが【有効】です。個別採点ページ等でテスト用の拡張操作が行えます。",
    "test_tool_missing": "ℹ️ テーブル全削除ロジック関数は、views/progress_mgmt.py内への配置をお待ちしています。",
    "test_mode_disabled": "⚪ 現在は通常の本番モードです。検証用の破壊的ツールは安全に封印されています。",
    "missing_db_records": "❌ 更新対象のデータがデータベースに存在しないため、処理を中断しました。新規追加は許可されていません。",
    "missing_ids": "💡 存在しない採点問題ID（先頭最大5件を表示）: {ids}",
    "csv_count_mismatch": "⚠️ CSVの件数（{csv_count}件）に対し、DBに存在するデータは（{db_count}件）しかありませんでした。",
    "database_initialize": "データベースを初期化中...",
    "question_previous_wrap": "🔄 現在地より手前に未採点・保留がないため、末尾に戻って逆引き検索しました。",
    "question_previous_none": "✨ 現在地より手前に未採点・保留データはありません。",
    "question_next_wrap": "🔄 現在地より後ろに未採点・保留がないため、先頭に戻って検索しました。",
    "question_next_none": "✨ この問題に含まれるすべての未採点・保留データは処理完了しています！",
    "question_save_success": "🟢 判定「{score}」で正常に保存しました！",
    "question_finish_title": "🎉 採点完了の確認",
    "question_finish_heading": "##### ✨ これで最後の採点が終了しました！",
    "question_finish_message": "最終判定の保存は完了しています。このまま問題一覧画面に戻りますか？それとも内容を見直しますか？",
    "question_finish_submit": "✅ このまま登録をして一覧に戻る",
    "question_review_again": "🔍 もう一度採点を見直す",
    "question_update_error": "データベースの更新に失敗しました: {error}",
    "ai_judgement": "AI判定: {status}",
    "status_no_data": "データなし",
    "status_correct": "🟢 正答(O)",
    "status_wrong": "🔴 誤答(X)",
    "status_none": "⚪ 無答(*)",
    "status_hold": "🟣 保留(H)",
    "no_data_value": "（データなし）",
    "ungraded_status": "⏳ 未採点",
    "confirmed_status": "確定済({status})",
    "memo": "採点メモ / コメント",
    "first_record_short": "⏪ 先頭へ戻る",
    "previous_unprocessed_short": "⏮️ 前の未採点へ",
    "next_unprocessed_short": "⏭️ 次の未採点へ",
    "answer_score_correct": "🟢 正答(O)",
    "answer_score_wrong": "🔴 誤答(X)",
    "answer_score_none": "⚪ 無答(*)",
    "answer_score_hold": "🟡 保留(H)",
    "unprocessed_preview": "##### 📊 抽出データプレビュー（先頭最大100件）",
}

# タブごとの表示許可ロール（タブ5をリーダー・特権用に設定する例：2=リーダー, 3=運用管理, 4=特権）
# 現場の運用に合わせて "1,2,3,4" など自由に変更してください。
TAB_ROLE_CONFIG = {
    "tab1": "1,2,3,4",
    "tab2": "2,3,4",
    "tab3": "4",
    "tab4": "",
    "tab5": "4" ,
    "tab6": "3,4",
    "tab7": "4"
}

#ログアウトするまでの時間（秒） （例：1800秒 ＝ 30分）
LOGIN_TIMEOUT_SECONDS = 300     #とりあえず15分か？ 　テストの時は300秒    
